### ISSUE TITLE
add listening time

### ISSUE THREAD

**Issue by jeffparla** [parlajatwit/wrapped-fm#1]
thinking of using this method with the date exactly a year ago
https://www.last.fm/api/show/user.getWeeklyTrackChart
i'm not sure if it gets every single track in that time, it would be a huge http request and their server probably hates it.
this may not even be possible unless i'm missing something or the developers of that api stop being mean

**Comment by parlajatwit** [comment]
done but could be implemented better with threads

**Comment by jeffparla** [comment]
done but could be implemented better with threads
