### ISSUE TITLE
add top genre

### ISSUE THREAD

**Issue by jeffparla** [parlajatwit/wrapped-fm#2]
a couple of approaches for this one
1. take every single track and use the musicbrainz id or something and find the genre, count up all the genres, then use the most common one.
2. same approach as above but for top albums
3. just use the genre from the top artist, i doubt people will notice the difference because they listen to artists of genres they like

**Comment by ShaziahGafur** [comment]
Hi @parlajatwit, I can work on this. Please assign it to me

**Comment by jeffparla** [comment]
not sure if you can get genre from the last.fm api so good luck

**Comment by jeffparla** [comment]
added in c311cb07a01aa0638000e05c120126dfca422dcb
leaving the issue open if you want to try and speed it up a bit
